mpbuilder {
  http {
    port = 8081
    port = ${?HTTP_PORT}
  }

  db {
    dataSourceClassName = org.postgresql.ds.PGSimpleDataSource
    dataSource {
      serverName = localhost
      serverName = ${?DB_HOST}
      portNumber = 5433
      portNumber = ${?DB_PORT}
      databaseName = mpbuilder
      databaseName = ${?DB_NAME}
      user = mpbuilder
      user = ${?DB_USER}
      password = mpbuilder
      password = ${?DB_PASSWORD}
    }
  }
}
