#!/usr/bin/env bash
# Regenerate the calculator's bundled stylesheet from the SPA's stylesheets.
#
# The calculator only needs the subset of modules/ui/src/main/resources/*.css
# that the shared product configurator actually uses; the manufacturing,
# catalog-editor, checkout, customer-portal, product-catalog, order-history,
# login and calendar stylesheets are deliberately left out.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SRC="$ROOT/modules/ui/src/main/resources"
OUT="$ROOT/modules/ui-calculator/src/main/resources/calculator.css"

# reset.css is deliberately absent: its `*` and `body` rules would restyle a
# host page. css/reset-scoped.css carries a `.mp-calculator`-scoped equivalent,
# kept here in the same position reset.css has in the SPA — before the component
# stylesheets. (It uses `:where()` so it does not out-rank them on specificity
# either; see the note in that file.)
PARTS=(tokens layout utilities uikit pricing basket)

{
  printf '/* Product Calculator — bundled stylesheet. DO NOT EDIT BY HAND.\n'
  printf ' *\n'
  printf ' * Generated by build-css.sh as:\n'
  printf ' *   modules/ui-calculator/css/reset-scoped.css\n'
  printf ' *   modules/ui/src/main/resources/{%s}.css\n' "$(IFS=,; echo "${PARTS[*]}")"
  printf ' *   modules/ui-calculator/css/shell.css\n'
  printf ' *\n'
  printf ' * Regenerate with modules/ui-calculator/build-css.sh after editing any of them.\n'
  printf ' */\n\n'
  printf '\n/* ================= reset-scoped.css ================= */\n'
  cat "$ROOT/modules/ui-calculator/css/reset-scoped.css"
  for f in "${PARTS[@]}"; do
    printf '\n/* ================= %s.css ================= */\n' "$f"
    cat "$SRC/$f.css"
  done
  printf '\n/* ================= shell.css ================= */\n'
  cat "$ROOT/modules/ui-calculator/css/shell.css"
} > "$OUT"

echo "Wrote $OUT ($(wc -c < "$OUT") bytes)"
